### ISSUE TITLE
Switch blake2b and ed25519 algorithm implementation

### ISSUE THREAD

**Issue by driftluo** [cryptape/cita-cli#101]
Maybe we can use these two libraries to do it, but please test compatibility before switching. The most important thing is that the `key` and `personal` values of `blake2b` algorithm are consistent with `cita-common`.

```toml
blake2b_simd = "0.4.1"
ed25519-dalek = "0.9.1"
```

After completion, we will be able to cancel conditional compilation and support three algorithms at the same time.
